{{- if source_only ~}}
#if !MYPACKAGE_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

{{~ end -}}
namespace MyPackage;

{{~ if source_only ~}}
[global::System.Diagnostics.DebuggerNonUserCode]
{{~ end ~}}
public class MyClass
{
}
